[general]
live_config_reload = false
import = [
    "~/.config/alacritty/themes/themes/moonfly.toml"
]

[window.dimensions]
columns = 200
lines = 60

[window.padding]
x = 20
y = 4

[window]
opacity = 0.75
blur = true

[font]
size = 14.0
normal = { family = "JetBrainsMono Nerd Font"}

[mouse]
hide_when_typing = false

