[window.dimensions]
columns = 200
lines = 60

[window.padding]
x = 20
y = 4

[window]
opacity = 0.4

[font]
size = 14.0

# [[keyboard.bindings]]
# key = "Comma"
# mods = "Command"
#
# [keyboard.bindings.command]
# args = ["-c", "open ~/.config/alacritty/alacritty.yml"]
# program = "sh"

# [[keyboard.bindings]]
# action = "SpawnNewInstance"
# key = "N"
# mods = "Command"
#
# [[keyboard.bindings]]
# chars = " "
# key = "Space"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u0015"
# key = "Back"
# mods = "Super"
#
# [[keyboard.bindings]]
# chars = "\u001Bb"
# key = "Left"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bf"
# key = "Right"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001BOH"
# key = "Left"
# mode = "AppCursor"
# mods = "Command"
#
# [[keyboard.bindings]]
# chars = "\u001BOF"
# key = "Right"
# mode = "AppCursor"
# mods = "Command"
#
# [[keyboard.bindings]]
# chars = "\u0011"
# key = "Q"
# mods = "Control"
