keypress_delay_ms: 20

modmap:
  - name: Global
    remap:
      CapsLock: LeftCtrl
      Space:  # Space as Shift
        held: Shift_L
        alone: Space
        free_hold: true
      RightShift: Grave

  - name: Not Mistel
    device:
      not: "MD600 Alpha"
    remap:
      LeftAlt: LeftCtrl

  - name: Mistel Specific
    device:
      only: "MD600 Alpha"
    remap:
      LeftAlt:
        held: LeftCtrl
        alone: Muhenkan
        free_hold: true
      RightAlt:
        held: RightCtrl
        alone: Henkan
        free_hold: true

keymap:
  - name: Mistel Specific
    device:
      only: "MD600 Alpha"
    remap:
      Control_R-h: left
      Control_R-l: right
      Control_R-k: up
      Control_R-j: down
