gui:
  showIcons: true
  nerdFontsVersion: "3"
  commitAuthorShortLength: 10
  commitAuthorLongLength: 10
  sidePanelWidth: 0.25
  showPanelJumps: false
  commandLogSize: 10
git:
  branchLogCmd: git log --graph --color=always --date=format:'%Y-%m-%d %H:%M' --pretty=format:'%C(green)%H%Creset %C(#dd4814)%an%Creset %C(white reverse)%d%Creset %n%C(cyan)%ad%Creset %s%Creset%n' {{branchName}} --
  allBranchesLogCmd: git log --graph --color=always --date=format:'%Y-%m-%d %H:%M' --pretty=format:'%C(green)%H%Creset %C(#dd4814)%an%Creset %C(white reverse)%d%Creset %n%C(cyan)%ad%Creset %s%Creset%n' --
