return {
    error_icon = " ",
    warn_icon = " ",
    hint_icon = "󰌵 ",
    info_icon = " ",
    modified_icon = " ",
    added_icon = " ",
    removed_icon = " ",
    deleted_icon = "",
    renamed_icon = "󰛂 ",
    untracked_icon = " ",
    ignored_icon = " ",
    unstaged_icon = " ",
    staged_icon = " ",
    conflict_icon = "",
    code_icon = " ",
    win_icon = " ",
    linux_icon = " ",
    mac_icon = " ",
    readonly_icon = "󰌾 ",
    branch_icon = " ",
}
