# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'alvan/vim-closetag'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-fall/fall.vim'

